"""create initial tables

Revision ID: a53089e44fe7
Revises: 
Create Date: 2026-06-28 11:25:33.196739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53089e44fe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('origin_department', sa.String(), nullable=False),
    sa.Column('origin_room', sa.String(), nullable=False),
    sa.Column('destination_department', sa.String(), nullable=False),
    sa.Column('equipment_needed', sa.String(), nullable=True),
    sa.Column('biohazard', sa.Boolean(), nullable=False),
    sa.Column('transporters_required', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_request_id', sa.Integer(), nullable=False),
    sa.Column('transporter_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transport_request_id'], ['transport_requests.id'], ),
    sa.ForeignKeyConstraint(['transporter_id'], ['transporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_assignment')
    op.drop_table('transporters')
    op.drop_table('transport_requests')
    # ### end Alembic commands ###
